name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: pack
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
              target
              !.fingerprint
              !build
              !deps
              !examples
              !incremental
              !target\*\.fingerprint
              !target\*\build
              !target\*\deps
              !target\*\examples
              !target\*\incremental
#    - name: Run tests
#      run: cargo test --verbose
